### ISSUE TITLE
Favor AbortController over CancelablePromise

### ISSUE THREAD

**Issue by jimmywarting** [alkemics/CancelablePromise#15]
Maybe mention in the readme that AbortController is better to use. It can be natively used with fetch to abort a request and can also be used for other things. there is also a polyfill for it.

**Comment by alk-sdavid** [comment]
I will mention AbortController and AbortSignal in the next release: https://github.com/alkemics/CancelablePromise/blame/66c362b2074e78c6a66442b5f0b6bc4db2c9347a/README.md#L12

...yes I know, it took so long 😅

**Comment by alk-sdavid** [comment]
https://github.com/alkemics/CancelablePromise/blame/master/README.md#L12
