### ISSUE TITLE
Finally callback is not invoked

### ISSUE THREAD

**Issue by hans-hsieh-asus** [alkemics/CancelablePromise#25]
Hi, the document says that the `finally` callback will always be invoked event if the promise is canceled. But for the following snippet:
```
const {CancelablePromise} = require('cancelable-promise');
const promise = new CancelablePromise((resolve, reject) => {
  // Do something important...
}).finally(() => console.log('finally is called'));
setTimeout(() => {
  console.log('about to cancel');
  promise.cancel();
  // Just wait
  setTimeout(() => {}, 100000);
}, 1000);
```
, the `finally is called` is not printed.
Do I misunderstand anything?

**Comment by sebastiendavid** [comment]
@hans-hsieh-asus I'll have a look

**Comment by sebastiendavid** [comment]
@hans-hsieh-asus Ok I see, it's because you never resolve your 1st promise, try this:

```javascript
const { CancelablePromise } = require('./dist/CancelablePromise');
const promise = new CancelablePromise((resolve, reject) => {
  setTimeout(resolve, 500);
})
  .then(() => {
    console.log('then is not called');
  })
  .finally(() => {
    console.log('finally is called');
  });
setTimeout(() => {
  console.log('about to cancel');
  promise.cancel();
  // Just wait
  setTimeout(() => {
    console.log('done');
  }, 1000);
}, 200);
```

I guess the doc is misleading, in fact the `CancelablePromise` is acting as a native `Promise`, if you're replacing the `CancelablePromise` by `Promise` in your original script (without the `promise.cancel()` of course), you'll have the same issue: `finally` will be never called.

**Comment by hans-hsieh-asus** [comment]
Thanks, I got it.  
But there's a usage scenario which I think is pretty likely to happen. 
Imagine that we have a function `doSomeJob()`, which returns a promise that resolves when the job is finished. 
The job will occupy some external resources. When the job is done, no matter because it's done, failed, or canceled, it should release the resource.
In such a scenario, because the `finally` block is not executed when the promise is canceled, we have no way to release the resource.
But if we change the behavior to call the `finally` block in such a case, it will break backward compatibility.  
How about we let the constructor `CancelablePromise` take a third optional argument? Maybe the argument could be something like [p-cancelable](https://github.com/sindresorhus/p-cancelable), so that we can do something when the promise is canceled?

**Comment by sebastiendavid** [comment]
Ok I see, I’ll try to do something about this before the end of this week.

**Comment by hans-hsieh-asus** [comment]
You rock!

**Comment by sebastiendavid** [comment]
@hans-hsieh-asus I tested 2 approaches:
- 1 similar to [p-cancelable](https://github.com/sindresorhus/p-cancelable) with the onCancel method in the promise executor:
```javascript
const promise = new CancelablePromise((resolve, reject, onCancel) => {
  onCancel(() => {
    console.log('👋');
  });
});
promise.cancel();
```
- and 1 which force finally callback execution when cancelling a promise.
```
const promise = new CancelablePromise((resolve, reject, onCancel) => {
  // no-op
}).finally(() => {
  console.log('👋');
}, true);
promise.cancel();
```
I can add these 2 solutions to the lib, what do you think?

**Comment by hans-hsieh-asus** [comment]
@sebastiendavid Thank you.
It looks like the behavior is as below:

	When a cancelable promise is canceled, the registered cancel functions are called. 
	If multiple cancel functions were registered, they are called in order.
	If `then` and `catch` blocks are skipped.
	For the `finally` blocks that have the 2nd argument given as `true`, the `finally` blocks are called in order.

It looks good to me. The only potential problem I could find is if in the future the official `Promise` also adds a second argument to the `finally`, it *may* cause a conflict if we want `CancelablePromise` be able to be used as a normal promise. But as this might never happen, I think it might not be a real problem.
👍

**Comment by sebastiendavid** [comment]
Another approach to avoir the finally 2nd argument: https://codesandbox.io/s/eloquent-sinoussi-5njtd?file=/src/App.tsx
```javascript
promise.finally(runWhenCanceled(() => {
  console.log('finally!');
}))
```

**Comment by hans-hsieh-asus** [comment]
Personally, the `onCancel` argument already fulfills my use case.
It looks like originally, even if a promise is canceled and the `resolve` or `reject` functions are called later, the `finally` callback will still be called. If we make the `finally` callback be called when it is canceled (either by using the second boolean argument or the `runWhenCanceled`), it will cause the callback to be called twice as shown below:
```
const promise = new CancelablePromise((resolve, reject, onCancel) => {
	setTimeout(() => resolve(), 5000);
  onCancel(() => {
	console.log("onCancel");
  });
}).then((res) => {
  console.log("then", res);
}).finally(() => {
  console.log('finally');
}).finally(runWhenCanceled(() => {
  console.log('finally oncancel');
}));

setTimeout(() => {
  console.log("cancel promise");
  promise.cancel();
}, 400);
```
The output will be
```
cancel promise 
onCancel 
finally oncancel 
finally 
finally oncancel 
```
This might be a little surprising to the users. (?)
How about it keeps the `cancel` callbacks to be separated from the `finally` callback? That is, the `cancel` callback won't be called when the promise is resolved or rejected. And regarding the way to register the `cancel` callback, in addition to the way `new CancelablePromise((resolve, reject, onCancel) => {...})`, another way that came into my mind is 
```
new CancelablePromise((resolve, reject) => {
  ...
}).onCancel(() => {
  console.log('cancel 1');
}).onCancel(() => {
  console.log('cancel 2');
});
```
Maybe `onCancel` is not a perfect word here. I'm not a native speaker. :(
This way might be more suited when people are using `cancelable()` function instead of `new CancelablePromise()`. (?)
```
cancelable(
  new Promise((resolve, reject) => {
    ...
  })
).onCancel(() => {
  console.log('cancel 1');
}).onCancel(() => {
  console.log('cancel 2');
});
```
It's just my opinion. Anyway works for me. 😃

**Comment by sebastiendavid** [comment]
Sorry for the delay, I published the last changes.

**Comment by hans-hsieh-asus** [comment]
Thank you. :)
