### ISSUE TITLE
Dont work with IE11

### ISSUE THREAD

**Issue by imnstr** [alkemics/CancelablePromise#81]
Tested with create-react-app here https://github.com/imnstr/cancelable-promise-issue
When **_CancelablePromise_** imported then i have message syntex error.
Library babel config preset with target ie11 exists, but dont works.
**How to reproduce:** start project via ### **npm run start** and go to ### **http://localhost:8080/** using Google Chrome and IE11.
**Expected:** Hello title on the page and no errors.
**Actual:** Syntax error in console.

**Comment by alk-sdavid** [comment]
Hi @imnstr, thank you for your report. Indeed `browser` export has been added recently in the last release (4.2.1): https://github.com/alkemics/CancelablePromise/commit/566e210762fe802e4099248dd5f2fccdd1d85895, it should fix the webpack build which resolves modules in this order: `browser`, `module` and `main`. Notice that you need a Promise polyfill for IE11, which is not included in your reproduction repo

![Screenshot 2021-07-12 at 15 45 58](https://user-images.githubusercontent.com/50570955/125298410-62c1d800-e328-11eb-9cf6-d16cc2fb28f9.png)

**Comment by imnstr** [comment]
Hi @alk-sdavid , good, release 4.2.1 resolved this issue, thank you!
